[hooks]
# TODO: Wait for 0.12 update on rusty-hook
# pre-commit = ["cargo clippy --locked -- -D warnings", "cargo fmt -- --check"]
pre-commit = "cargo clippy --locked -- -D warnings"

[logging]
verbose = true
