[package]
name = "libpsmt"
authors = [ "Pablo Hernandez (@Hadronomy)" ]
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.16.0"
libpsmt-impl = { version = "0.1.0", path = "../libpsmt-impl" }
termination = "0.1.2"
thiserror = "1.0.38"
