[package]
name = "libpsmt"
authors = [ "Pablo Hernandez (@Hadronomy)" ]
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.8"
git2 = "0.16.0"
libpsmt-proc = { version = "0.1.0", path = "../libpsmt-proc" }
termination = "0.1.2"
thiserror = "1.0.38"
