[package]
name = "libpsmt"
authors = [ "Pablo Hernandez (@Hadronomy)" ]
version = "0.1.0"
edition = "2021"

[dependencies]
libpsmt-impl = { version = "0.1.0", path = "../libpsmt-impl" }
thiserror = "1.0.38"
